apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-rsqe
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-rsqe
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-rsqe
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-rsqe
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-rsqe
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-kcbm-tenant/rhtap-demo-app/hacbs-test-project-rsqe@sha256:a0127769fe4c6200e8e89e0ce726b804a229046175e5dd79d5b225d083413992
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
